/*
 * ScrabbleBoardPanel.java
 *
 * Created on November 10, 2007, 2:02 PM
 */
package gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeListener;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import scrabbletools.BoardLayout;
import scrabbletools.LetterScores;

/**
 *
 * @author  Nick
 */
public class ScrabbleBoardPanel extends javax.swing.JPanel {

    public static final int ROWS = 15;
    public static final int COLS = 15;
    /** Creates new form ScrabbleBoardPanel */

    public ScrabbleBoardPanel() {
        initComponents();
        GridLayout gl = new GridLayout();
        gl.setColumns(15);
        gl.setRows(15);
        gl.setVgap(0);
        gl.setHgap(0);
        setLayout(gl);
        initializeTiles();
        getInputMap(WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("VK_WINDOWS"),
                "INDICATEWORKED");
        getActionMap().put("INDICATEWORKED", new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        
    }
    
    public void paint(Graphics g) {
        super.paint(g);
        int rowMult = getHeight() / ROWS;
        int colMult = getWidth() / COLS;
        g.setColor(Color.BLACK);
        for (int row = 0; row < (ROWS + 1); row++) {
            int currentY = row * rowMult;
            if (row == ROWS) {
                currentY--;
            }
            g.drawLine(0, currentY, getWidth(), currentY);
        }
        for (int col = 0; col <= COLS; col++) {
            int currentX = col * colMult;
            if (currentX == getWidth()) {
                currentX--;
            }
            g.drawLine(currentX, 0, currentX, getHeight());
        }
    }

    public void initializeTiles() {
        VisibleTile[][] tiles = new VisibleTile[((GridLayout) getLayout()).getRows()][];
        for (int row = 0; row < ((GridLayout) getLayout()).getRows(); row++) {
            tiles[row] = new VisibleTile[((GridLayout) getLayout()).getColumns()];
            for (int col = 0; col < ((GridLayout) getLayout()).getColumns(); col++) {
                tiles[row][col] = new VisibleTile(BoardLayout.charBoardValues[row][col],
                        LetterScores.EMPTY_SQUARE);
                add(tiles[row][col]);
                tiles[row][col].letter = LetterScores.EMPTY_SQUARE;
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(450, 450));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
